language: shell
sudo: false

install:
  - export scversion="v0.4.7" # or "stable", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
  - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
  - cp shellcheck-"${scversion}"/shellcheck /tmp/

script:
  - /tmp/shellcheck --version # for reference
  - PATH=/tmp:$PATH make shellcheck | tee shellcheck-results.log
  - test "$(wc -c < shellcheck-results.log)" -eq 0
